config/routes.rb
Rails.application.routes.draw do

  namespace :gtf do
    resources :video_encodings
    resources :users, except: [:show]
    resources :upload_extensions, except: [:show]
    resources :upload_actions, except: [:show]
    resources :storages, except: [:show]
    resources :scene_keywords, except: [:show]
    resources :scene_genres, except: [:show]
    resources :scenes, except: [:show]
    resources :permission_groups, except: [:show]
    resources :models, except: [:show]
    resources :media_types, except: [:show]
    resources :media, except: [:show]
    resources :lines, except: [:show]
    resources :labels, except: [:show]
    resources :image_encodings, except: [:show]
    resources :image_encodeds, except: [:show]
    resources :file_object_types, except: [:show]
    resources :file_object_type_families, except: [:show]
    resources :encoder_servers, except: [:show]
    resources :directors, except: [:show]
    resources :content_releases, except: [:show]
    resources :contents, shallow: true, except: [:show] do
      resources :videos, shallow: true, except: [:show] do
        resources :video_files, except: [:show]
      end
      resources :images, shallow: true, except: [:show] do
        resources :image_files, except: [:show]
      end
      resources :uploads
    end
    resources :content_types, except: [:show]
    resources :content_price_rates, except: [:show]
    resources :configurations, except: [:show]
    resources :companies, except: [:show]
    resources :agents, except: [:show]
  end

  namespace :shared do
    resources :websites
    resources :currencies
    resources :countries
  end

  namespace :idcert do
    resources :website_users
  end

  get 'welcome/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: 'welcome#index'

end

app/models/gtf.rb
module Gtf
  def self.table_name_prefix
    'gtf_'
  end
end

app/models/gtf/agent.rb
class Gtf::Agent < Gtf::Base
  self.table_name = "agent"
end

app/models/gtf/base.rb
class Gtf::Base < ActiveRecord::Base
  self.abstract_class = true
  self.establish_connection "#{Rails.env}".to_sym
end

app/models/gtf/company.rb
class Gtf::Company < Gtf::Base
  self.table_name = "company"
end

app/models/gtf/configuration.rb
class Gtf::Configuration < Gtf::Base
  self.table_name = "config"
end

app/models/gtf/content.rb
class Gtf::Content < Gtf::Base
  self.table_name = "content"
  default_scope ->{ order(:content_id => :desc) }
  belongs_to :content_type, class_name: 'Gtf::ContentType'
  has_one :scene
  has_many :videos, class_name: "Gtf::Video"
  has_many :images, class_name: "Gtf::Image"
  has_many :uploads, class_name: "Gtf::Upload"
end

app/models/gtf/content_price_rate.rb
class Gtf::ContentPriceRate < Gtf::Base
  self.table_name = "content_price_rate"
  belongs_to :content, class_name: "Gtf::Content"
end

app/models/gtf/content_release.rb
class Gtf::ContentRelease < Gtf::Base
  self.table_name = "content_release"
  belongs_to :website, class_name: 'Shared::Website'
  belongs_to :content, class_name: 'Gtf::Content'
end

app/models/gtf/content_type.rb
class Gtf::ContentType < Gtf::Base
  self.table_name = "content_type"
end

app/models/gtf/director.rb
class Gtf::Director < Gtf::Base
  self.table_name = "director"
  belongs_to :company, class_name: 'Gtf::Company'
end

app/models/gtf/encoder_server.rb
class Gtf::EncoderServer < Gtf::Base
  self.table_name = "encoder_server"
end

app/models/gtf/file_object_type.rb
class Gtf::FileObjectType < Gtf::Base
  self.table_name = "file_object_type"
  belongs_to :content_type, class_name: "Gtf::ContentType"
  belongs_to :file_object_type_family, class_name: "Gtf::FileObjectTypeFamily"
  belongs_to :secondary_content_type, class_name: "Gtf::SecondaryContentType"
end

app/models/gtf/file_object_type_family.rb
class Gtf::FileObjectTypeFamily < Gtf::Base
  self.table_name = "file_object_type_family"
end

app/models/gtf/image.rb
class Gtf::Image < Gtf::Base

  include Created
  include SourceVideoFile

  self.table_name = "image"
  belongs_to :company, class_name: "Gtf::Company"
  belongs_to :content, class_name: "Gtf::Content"
  belongs_to :file_object_type, class_name: "Gtf::FileObjectType"
  belongs_to :director, class_name: "Gtf::Director"
  belongs_to :storage, class_name: "Gtf::Storage"
  belongs_to :upload, class_name: "Gtf::Upload"
  belongs_to :user, class_name: "Gtf::User"
  has_many :image_files, class_name: "Gtf::ImageFile"

  before_create :set_created

end

app/models/gtf/image_encoded.rb
class Gtf::ImageEncoded < Gtf::Base
  self.table_name = "image_encoded"
  belongs_to :encoder_server, class_name: "Gtf::EncoderServer"
  belongs_to :image_encoding, class_name: "Gtf::ImageEncoding"
  belongs_to :image, class_name: "Gtf::Image"
end

app/models/gtf/image_encoding.rb
class Gtf::ImageEncoding < Gtf::Base
  self.table_name = "image_encoding"
  belongs_to :upload_extension, class_name: "Gtf::UploadExtension"
end

app/models/gtf/image_file.rb
class Gtf::ImageFile < Gtf::MediaFile

  include SourceVideoFile

  self.table_name = "image_file"
  belongs_to :media, class_name: "Gtf::Media"
  belongs_to :image_encoding, class_name: "Gtf::ImageEncoding"
  belongs_to :image, class_name: "Gtf::Image"

  private

    def parent
      self.image
    end

    def encoding_id
      self.image_encoding_id
    end

end

app/models/gtf/label.rb
class Gtf::Label < Gtf::Base
  self.table_name = "label"
  belongs_to :company, class_name: "Gtf::Company"
end

app/models/gtf/line.rb
class Gtf::Line < Gtf::Base
  self.table_name = "line"
  belongs_to :company, class_name: "Gtf::Company"
  belongs_to :content, class_name: "Gtf::Content"
  belongs_to :label, class_name: "Gtf::Label"
end

app/models/gtf/media.rb
class Gtf::Media < Gtf::Base
  self.table_name = "media"
  belongs_to :company, class_name: "Gtf::Company"
  has_one :media, class_name: "Gtf::Media"
end

app/views/gtf/encoder_servers/_form.html.slim
= form_for @encoder_server do |f|
  - if @encoder_server.errors.any?
    #error_explanation
      h2 = "#{pluralize(@encoder_server.errors.count, "error")} prohibited this gtf_encoder_server from being saved:"
      ul
        - @encoder_server.errors.full_messages.each do |message|
          li = message
  .row
    .medium-6.columns
      = label_tag :name
      = f.text_field :name, autofocus: true, placeholder: 'Enter encoder server name'
      = label_tag :description
      = f.text_field :description, placeholder: 'Enter encoder server description'
      = label_tag :status
      = f.select :status, ["busy", "free"], selected: @encoder_server.status
      = label_tag :is_usable
      = f.check_box :is_usable, {}, "yes", "no"
      p
        = f.button "Save", class: "button"

app/views/gtf/encoder_servers/edit.html.slim
.columns
  h1 Editing encoder server #{@encoder_server.encoder_server_id}

  = render 'form'

  = link_to 'Back', gtf_encoder_servers_path

app/views/gtf/encoder_servers/index.html.slim
h1 Encoder servers

= link_to 'Create encoder server', new_gtf_encoder_server_path
table
  thead
    tr
      th ID
      th Name
      th Description
      th Status
      th Usable
      th
  tbody
    - @encoder_servers.each do |encoder_server|
      tr
        td = link_to encoder_server.encoder_server_id, edit_gtf_encoder_server_path(encoder_server)
        td = encoder_server.name
        td = encoder_server.description
        td = encoder_server.status
        td = enabled_or_disabled(encoder_server.is_usable)
        td.delete
          = link_to encoder_server, data: { confirm: 'Are you sure?' }, method: :delete
            = fa_icon "close", class: ["close"]

= paginate @encoder_servers

app/views/gtf/encoder_servers/new.html.slim
.columns
  h1 New encoder server

  = render 'form'

  = link_to 'Back', gtf_encoder_servers_path