config/routes.rb
Rails.application.routes.draw do

  namespace :gtf do
    resources :video_encodings
    resources :users, except: [:show]
    resources :upload_extensions, except: [:show]
    resources :upload_actions, except: [:show]
    resources :storages, except: [:show]
    resources :scene_keywords, except: [:show]
    resources :scene_genres, except: [:show]
    resources :scenes, except: [:show]
    resources :permission_groups, except: [:show]
    resources :models, except: [:show]
    resources :media_types, except: [:show]
    resources :media, except: [:show]
    resources :lines, except: [:show]
    resources :labels, except: [:show]
    resources :image_encodings, except: [:show]
    resources :image_encodeds, except: [:show]
    resources :file_object_types, except: [:show]
    resources :file_object_type_families, except: [:show]
    resources :encoder_servers, except: [:show]
    resources :directors, except: [:show]
    resources :content_releases, except: [:show]
    resources :contents, shallow: true, except: [:show] do
      resources :videos, shallow: true, except: [:show] do
        resources :video_files, except: [:show]
      end
      resources :images, shallow: true, except: [:show] do
        resources :image_files, except: [:show]
      end
      resources :uploads
    end
    resources :content_types, except: [:show]
    resources :content_price_rates, except: [:show]
    resources :configurations, except: [:show]
    resources :companies, except: [:show]
    resources :agents, except: [:show]
  end

  namespace :shared do
    resources :websites
    resources :currencies
    resources :countries
  end

  namespace :idcert do
    resources :website_users
  end

  get 'welcome/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: 'welcome#index'

end

app/models/gtf.rb
module Gtf
  def self.table_name_prefix
    'gtf_'
  end
end

app/models/gtf/agent.rb
class Gtf::Agent < Gtf::Base
  self.table_name = "agent"
end

app/models/gtf/base.rb
class Gtf::Base < ActiveRecord::Base
  self.abstract_class = true
  self.establish_connection "#{Rails.env}".to_sym
end

app/models/gtf/company.rb
class Gtf::Company < Gtf::Base
  self.table_name = "company"
end

app/models/gtf/configuration.rb
class Gtf::Configuration < Gtf::Base
  self.table_name = "config"
end

app/models/gtf/content.rb
class Gtf::Content < Gtf::Base
  self.table_name = "content"
  default_scope ->{ order(:content_id => :desc) }
  belongs_to :content_type, class_name: 'Gtf::ContentType'
  has_one :scene
  has_many :videos, class_name: "Gtf::Video"
  has_many :images, class_name: "Gtf::Image"
  has_many :uploads, class_name: "Gtf::Upload"
end

app/models/gtf/content_price_rate.rb
class Gtf::ContentPriceRate < Gtf::Base
  self.table_name = "content_price_rate"
  belongs_to :content, class_name: "Gtf::Content"
end

app/models/gtf/content_release.rb
class Gtf::ContentRelease < Gtf::Base
  self.table_name = "content_release"
  belongs_to :website, class_name: 'Shared::Website'
  belongs_to :content, class_name: 'Gtf::Content'
end

app/models/gtf/content_type.rb
class Gtf::ContentType < Gtf::Base
  self.table_name = "content_type"
end

app/models/gtf/director.rb
class Gtf::Director < Gtf::Base
  self.table_name = "director"
  belongs_to :company, class_name: 'Gtf::Company'
end

app/models/gtf/encoder_server.rb
class Gtf::EncoderServer < Gtf::Base
  self.table_name = "encoder_server"
end

app/models/gtf/file_object_type.rb
class Gtf::FileObjectType < Gtf::Base
  self.table_name = "file_object_type"
  belongs_to :content_type, class_name: "Gtf::ContentType"
  belongs_to :file_object_type_family, class_name: "Gtf::FileObjectTypeFamily"
  belongs_to :secondary_content_type, class_name: "Gtf::SecondaryContentType"
end

app/models/gtf/file_object_type_family.rb
class Gtf::FileObjectTypeFamily < Gtf::Base
  self.table_name = "file_object_type_family"
end

app/models/gtf/image.rb
class Gtf::Image < Gtf::Base

  include Created
  include SourceVideoFile

  self.table_name = "image"
  belongs_to :company, class_name: "Gtf::Company"
  belongs_to :content, class_name: "Gtf::Content"
  belongs_to :file_object_type, class_name: "Gtf::FileObjectType"
  belongs_to :director, class_name: "Gtf::Director"
  belongs_to :storage, class_name: "Gtf::Storage"
  belongs_to :upload, class_name: "Gtf::Upload"
  belongs_to :user, class_name: "Gtf::User"
  has_many :image_files, class_name: "Gtf::ImageFile"

  before_create :set_created

end

app/models/gtf/image_encoded.rb
class Gtf::ImageEncoded < Gtf::Base
  self.table_name = "image_encoded"
  belongs_to :encoder_server, class_name: "Gtf::EncoderServer"
  belongs_to :image_encoding, class_name: "Gtf::ImageEncoding"
  belongs_to :image, class_name: "Gtf::Image"
end

app/models/gtf/image_encoding.rb
class Gtf::ImageEncoding < Gtf::Base
  self.table_name = "image_encoding"
  belongs_to :upload_extension, class_name: "Gtf::UploadExtension"
end

app/models/gtf/image_file.rb
class Gtf::ImageFile < Gtf::MediaFile

  include SourceVideoFile

  self.table_name = "image_file"
  belongs_to :media, class_name: "Gtf::Media"
  belongs_to :image_encoding, class_name: "Gtf::ImageEncoding"
  belongs_to :image, class_name: "Gtf::Image"

  private

    def parent
      self.image
    end

    def encoding_id
      self.image_encoding_id
    end

end

app/models/gtf/label.rb
class Gtf::Label < Gtf::Base
  self.table_name = "label"
  belongs_to :company, class_name: "Gtf::Company"
end

app/models/gtf/line.rb
class Gtf::Line < Gtf::Base
  self.table_name = "line"
  belongs_to :company, class_name: "Gtf::Company"
  belongs_to :content, class_name: "Gtf::Content"
  belongs_to :label, class_name: "Gtf::Label"
end

app/models/gtf/media.rb
class Gtf::Media < Gtf::Base
  self.table_name = "media"
  belongs_to :company, class_name: "Gtf::Company"
  has_one :media, class_name: "Gtf::Media"
end

app/views/gtf/videos/_form.html.slim
- @video = @video.nil? ? video : @video
= form_for @video, url: url do |f|
  - if @video.errors.any?
    #error_explanation
      h2 = "#{pluralize(@video.errors.count, "error")} prohibited this gtf_video from being saved:"
      ul
        - @video.errors.full_messages.each do |message|
          li = message
  .row
    .medium-6.columns
      = label_tag :upload_id
      = f.number_field :upload_id, autofocus: true, placeholder: "Enter upload ID"
      = label_tag :file_object_type_id
      = fill_select(@video.file_object_type, Gtf::FileObjectType, f)
      = label_tag :company_id
      = fill_select(@video.company, Gtf::Company, f)
      = label_tag :user_id
      = fill_select(@video.user, Gtf::User, "username", f)
      = label_tag :content_id
      = f.number_field :content_id, placeholder: "Enter content ID"
      / = label_tag :secondary_content_id
      / secondary_content_id     | int(11) unsigned
      = label_tag :storage_id
      = fill_select(@video.storage, Gtf::Storage, "storage_id", f)
      = label_tag :subpath
      = f.text_field :subpath, placeholder: "Enter subpath"
      = label_tag :url
      = f.text_field :url, placeholder: "Enter url"
      = label_tag :video_order
      = f.number_field :video_order, placeholder: "Enter video_order"
      - unless @video.video_id.nil?
        = label_tag :created
        = f.datetime_local_field :created
      = label_tag :status
      = f.select :status, ['active','archive'], selected: @video.status, placeholder: "Select status"
      = label_tag :subscription_news_state
      = f.select :subscription_news_state, ['waiting','processed'], selected: @video.subscription_news_state, placeholder: "Select subscription news state"
      = label_tag :exporting_to_dmca_status
      = f.select :exporting_to_dmca_status, ['started','exported'], selected: @video.exporting_to_dmca_status, placeholder: "Select exporting to DMCA status"
      p
        = f.button "Save", class: "button"

app/views/gtf/videos/_video.html.slim
video.video-js.vjs-default-skin(id="video_#{video.video_id}" data-setup='{}' width=300 controls preload="auto" poster="later add thumbnail")
  p.vjs-no-js
    | To view this video please enable JavaScript, and consider upgrading to a web browser that
    a(href="http://videojs.com/html5-video-support/" target="_blank") supports HTML5 video
  - video.video_files.each do |video_file|
    - if video_file.encode_status == "ok"
      source(src=video_file.url type='video/mp4' label="#{video_file.height}p")

app/views/gtf/videos/edit.html.slim
.columns
  h1 Video #{@video.video_id}

  ul#video_tabs.tabs(data-tabs)
    li.tabs-title.is-active
      a(href="#video_info_tab" aria-selected="true") Edit video info
    - if (@video.video_files && @video.video_files.length > 0)
      li.tabs-title
        a(href="#video_files_tab") Video files

  .tabs-video(data-tabs-content="video_tabs")
    #video_info_tab.tabs-panel.is-active
      = render 'form', url: @video
    - if (@video.video_files && @video.video_files.length > 0)
      #video_files_tab.tabs-panel
        = render file: "gtf/video_files/index", locals: {video_files: @video.video_files}

  = link_to 'Back', edit_gtf_content_path(@content)

app/views/gtf/videos/index.html.slim
h1 Videos
- @videos = @videos.nil? ? videos : @videos
= link_to 'Create video', new_gtf_content_video_path(@content)
.table-scroll
  table
    thead
      tr
        th ID
        th
        th Upload ID
        th File object type ID
        th Company ID
        th User ID
        th Content ID
        / th Secondary content ID
        th Storage ID
        th Subpath
        th Url
        th Video order
        th Created
        th Status
        th Subscription news state
        th Exporting to dmca status
        th
    tbody
      - @videos.each do |video|
        tr
          td = link_to video.video_id, edit_gtf_video_path(video)
          td
            == render video
          td = link_to_edit_resource(video.upload, "upload_id")
          td = link_to_edit_resource(video.file_object_type, "name")
          td = link_to_edit_resource(video.company, "name")
          td = link_to_edit_resource(video.user, "name")
          td = link_to_edit_resource(video.content, "content_id")
          / td = video.secondary_content_id
          td = video.storage_id
          td = video.subpath
          td = video.url
          td = video.video_order
          td = video.created
          td = video.status
          td = video.subscription_news_state
          td = video.exporting_to_dmca_status
          td.delete
            = link_to gtf_video_path(video), data: { confirm: 'Are you sure?' }, method: :delete
              = fa_icon "close", class: ["close"]

/ if videos where opened as videos, not in the content tab
- if @content.nil?
  = paginate @videos

app/views/gtf/videos/new.html.slim
.row
  .columns
    h1 New video

    = render 'form', url: gtf_content_videos_path(@content)

    = link_to 'Back', edit_gtf_content_path(@content)