config/routes.rb
Rails.application.routes.draw do

  namespace :gtf do
    resources :video_encodings
    resources :users, except: [:show]
    resources :upload_extensions, except: [:show]
    resources :upload_actions, except: [:show]
    resources :storages, except: [:show]
    resources :scene_keywords, except: [:show]
    resources :scene_genres, except: [:show]
    resources :scenes, except: [:show]
    resources :permission_groups, except: [:show]
    resources :models, except: [:show]
    resources :media_types, except: [:show]
    resources :media, except: [:show]
    resources :lines, except: [:show]
    resources :labels, except: [:show]
    resources :image_encodings, except: [:show]
    resources :image_encodeds, except: [:show]
    resources :file_object_types, except: [:show]
    resources :file_object_type_families, except: [:show]
    resources :encoder_servers, except: [:show]
    resources :directors, except: [:show]
    resources :content_releases, except: [:show]
    resources :contents, shallow: true, except: [:show] do
      resources :videos, shallow: true, except: [:show] do
        resources :video_files, except: [:show]
      end
      resources :images, shallow: true, except: [:show] do
        resources :image_files, except: [:show]
      end
      resources :uploads
    end
    resources :content_types, except: [:show]
    resources :content_price_rates, except: [:show]
    resources :configurations, except: [:show]
    resources :companies, except: [:show]
    resources :agents, except: [:show]
  end

  namespace :shared do
    resources :websites
    resources :currencies
    resources :countries
  end

  namespace :idcert do
    resources :website_users
  end

  get 'welcome/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: 'welcome#index'

end

app/models/gtf.rb
module Gtf
  def self.table_name_prefix
    'gtf_'
  end
end

app/models/gtf/agent.rb
class Gtf::Agent < Gtf::Base
  self.table_name = "agent"
end

app/models/gtf/base.rb
class Gtf::Base < ActiveRecord::Base
  self.abstract_class = true
  self.establish_connection "#{Rails.env}".to_sym
end

app/models/gtf/company.rb
class Gtf::Company < Gtf::Base
  self.table_name = "company"
end

app/models/gtf/configuration.rb
class Gtf::Configuration < Gtf::Base
  self.table_name = "config"
end

app/models/gtf/content.rb
class Gtf::Content < Gtf::Base
  self.table_name = "content"
  default_scope ->{ order(:content_id => :desc) }
  belongs_to :content_type, class_name: 'Gtf::ContentType'
  has_one :scene
  has_many :videos, class_name: "Gtf::Video"
  has_many :images, class_name: "Gtf::Image"
  has_many :uploads, class_name: "Gtf::Upload"
end

app/models/gtf/content_price_rate.rb
class Gtf::ContentPriceRate < Gtf::Base
  self.table_name = "content_price_rate"
  belongs_to :content, class_name: "Gtf::Content"
end

app/models/gtf/content_release.rb
class Gtf::ContentRelease < Gtf::Base
  self.table_name = "content_release"
  belongs_to :website, class_name: 'Shared::Website'
  belongs_to :content, class_name: 'Gtf::Content'
end

app/models/gtf/content_type.rb
class Gtf::ContentType < Gtf::Base
  self.table_name = "content_type"
end

app/models/gtf/director.rb
class Gtf::Director < Gtf::Base
  self.table_name = "director"
  belongs_to :company, class_name: 'Gtf::Company'
end

app/models/gtf/encoder_server.rb
class Gtf::EncoderServer < Gtf::Base
  self.table_name = "encoder_server"
end

app/models/gtf/file_object_type.rb
class Gtf::FileObjectType < Gtf::Base
  self.table_name = "file_object_type"
  belongs_to :content_type, class_name: "Gtf::ContentType"
  belongs_to :file_object_type_family, class_name: "Gtf::FileObjectTypeFamily"
  belongs_to :secondary_content_type, class_name: "Gtf::SecondaryContentType"
end

app/models/gtf/file_object_type_family.rb
class Gtf::FileObjectTypeFamily < Gtf::Base
  self.table_name = "file_object_type_family"
end

app/models/gtf/image.rb
class Gtf::Image < Gtf::Base

  include Created
  include SourceVideoFile

  self.table_name = "image"
  belongs_to :company, class_name: "Gtf::Company"
  belongs_to :content, class_name: "Gtf::Content"
  belongs_to :file_object_type, class_name: "Gtf::FileObjectType"
  belongs_to :director, class_name: "Gtf::Director"
  belongs_to :storage, class_name: "Gtf::Storage"
  belongs_to :upload, class_name: "Gtf::Upload"
  belongs_to :user, class_name: "Gtf::User"
  has_many :image_files, class_name: "Gtf::ImageFile"

  before_create :set_created

end

app/models/gtf/image_encoded.rb
class Gtf::ImageEncoded < Gtf::Base
  self.table_name = "image_encoded"
  belongs_to :encoder_server, class_name: "Gtf::EncoderServer"
  belongs_to :image_encoding, class_name: "Gtf::ImageEncoding"
  belongs_to :image, class_name: "Gtf::Image"
end

app/models/gtf/image_encoding.rb
class Gtf::ImageEncoding < Gtf::Base
  self.table_name = "image_encoding"
  belongs_to :upload_extension, class_name: "Gtf::UploadExtension"
end

app/models/gtf/image_file.rb
class Gtf::ImageFile < Gtf::MediaFile

  include SourceVideoFile

  self.table_name = "image_file"
  belongs_to :media, class_name: "Gtf::Media"
  belongs_to :image_encoding, class_name: "Gtf::ImageEncoding"
  belongs_to :image, class_name: "Gtf::Image"

  private

    def parent
      self.image
    end

    def encoding_id
      self.image_encoding_id
    end

end

app/models/gtf/label.rb
class Gtf::Label < Gtf::Base
  self.table_name = "label"
  belongs_to :company, class_name: "Gtf::Company"
end

app/models/gtf/line.rb
class Gtf::Line < Gtf::Base
  self.table_name = "line"
  belongs_to :company, class_name: "Gtf::Company"
  belongs_to :content, class_name: "Gtf::Content"
  belongs_to :label, class_name: "Gtf::Label"
end

app/models/gtf/media.rb
class Gtf::Media < Gtf::Base
  self.table_name = "media"
  belongs_to :company, class_name: "Gtf::Company"
  has_one :media, class_name: "Gtf::Media"
end

app/views/gtf/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this gtf_user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message
  .row
    .medium-6.columns
      = label_tag :username
      = f.text_field :username, autofocus: true, placeholder: "Enter username"
      = label_tag :permission_group_id
      = fill_select(@user.permission_group, Gtf::PermissionGroup, f)
      = label_tag :company_id
      = fill_select(@user.company, Gtf::Company, f)
      = label_tag :source_password, "Password"
      = f.password_field :source_password, autocomplete: "off", placeholder: "Enter password"
      = label_tag :source_password_confirmation, "Password confirmation"
      = f.password_field :source_password_confirmation, autocomplete: "off", placeholder: "Confirm password"
      = label_tag :name
      = f.text_field :name, placeholder: "Enter name"
      = label_tag :surname
      = f.text_field :surname, placeholder: "Enter surname"
      = label_tag :email
      = f.email_field :email, placeholder: "Enter email"
      = label_tag :phone
      = f.telephone_field :phone, placeholder: "Enter phone"
      = label_tag :mobile_phone
      = f.telephone_field :mobile_phone, placeholder: "Enter mobile phone"
      = label_tag :description
      = f.text_field :description, placeholder: "Enter description"
      = label_tag :enabled
      = f.check_box :enabled, {}, "yes", "no"
      br
      / = label_tag :disabled
      / = f.check_box :disabled, {autofocus: true}, "1", "0"
      - unless @user.user_id.nil?
        = label_tag :created
        = f.datetime_local_field :created
      = label_tag :last_login
      = f.datetime_local_field :last_login
      = label_tag :language
      = f.number_field :language, placeholder: "Enter language"
      = label_tag :ftp_password
      = f.password_field :ftp_password, autocomplete: "off", placeholder: "Enter ftp password"
      = label_tag :ftp_uid
      = f.number_field :ftp_uid, placeholder: "Enter ftp uid"
      = label_tag :ftp_gid
      = f.number_field :ftp_gid, placeholder: "Enter ftp gid"
      = label_tag :ftp_homedir
      = f.text_field :ftp_homedir, placeholder: "Enter ftp homedir"
      = label_tag :ftp_shell
      = f.text_field :ftp_shell, placeholder: "Enter ftp shell"
      = label_tag :ftp_expiration
      = f.datetime_local_field :ftp_expiration
      = label_tag :ftp_lastlogin
      = f.datetime_local_field :ftp_lastlogin
      = label_tag :ftp_lastlogout
      = f.datetime_local_field :ftp_lastlogout
      = label_tag :ftp_count
      = f.number_field :ftp_count, placeholder: "Enter ftp count"
      = label_tag :reg_ip
      = f.text_field :reg_ip, placeholder: "Enter reg_ip"
      = label_tag :reg_ip_location
      = f.text_field :reg_ip_location, placeholder: "Enter reg_ip_location"
      = label_tag :hide_poll
      = f.check_box :hide_poll, {}, "YES", "NO"
      p
        = f.button "Save", class: "button"

app/views/gtf/users/edit.html.slim
.columns
  h1 Editing user #{@user.username}

  == render 'form'

  = link_to 'Show', @user
  '|
  = link_to 'Back', gtf_users_path

app/views/gtf/users/index.html.slim
h1 Users

= link_to 'Create user', new_gtf_user_path
.table-scroll
  table
    thead
      tr
        th ID
        th Permisssion group
        th Company
        th Username
        th Full name
        th Email
        th Phone
        th Mobile phone
        th Description
        th Enabled
        th Disabled
        th Created
        th Last login
        th Language
        / th FTP password
        th FTP UID
        th FTP GUID
        th FTP homedir
        th FTP shell
        th FTP expiration
        th FTP last login
        th FTP last logout
        th FTP count
        th Registration IP
        th Registration location
        th Hide poll
        th
    tbody
      - @users.each do |user|
        tr
          td = link_to user.user_id, edit_gtf_user_path(user)
          td = link_to_edit_resource(user.permission_group, "name")
          td = link_to_edit_resource(user.company, "name")
          td = user.username
          td = full_name(user)
          td = user.email
          td = user.phone
          td = user.mobile_phone
          td = user.description
          td = enabled_or_disabled(user.enabled)
          td = enabled_or_disabled(user.disabled)
          td = user.created
          td = user.last_login
          td = user.language
          / td = user.ftp_password
          td = user.ftp_uid
          td = user.ftp_gid
          td = user.ftp_homedir
          td = user.ftp_shell
          td = user.ftp_expiration
          td = user.ftp_lastlogin
          td = user.ftp_lastlogout
          td = user.ftp_count
          td = user.reg_ip
          td = user.reg_ip_location
          td = user.hide_poll
          td.delete
            = link_to user, data: { confirm: 'Are you sure?' }, method: :delete
              = fa_icon "close", class: ["close"]

= paginate @users

app/views/gtf/users/new.html.slim
.row
  .columns
    h1 New user

    == render 'form'

    = link_to 'Back', gtf_users_path